// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iodrnzhzcfedfhcaksim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZHJuemh6Y2ZlZGZoY2Frc2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjY5MzgsImV4cCI6MjA3MTMwMjkzOH0.oJPOvStAfCJP4Km2AODADgN9DN8SnTQa2zLkLFqlX8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});